#!/bin/bash
# EC2 User Data Script — Initialize Petalia API on launch
# This script runs once per instance with root privileges

set -euo pipefail

# Logging
exec > /var/log/user-data.log 2>&1
echo "=== Petalia API User Data Script Started at $(date) ==="

# ============================================================================
# Install Docker (if not already installed on AMI)
# ============================================================================

if ! command -v docker &> /dev/null; then
  echo "Installing Docker..."
  amazon-linux-extras install -y docker
  systemctl start docker
  systemctl enable docker
  usermod -aG docker ec2-user
else
  echo "Docker already installed: $(docker --version)"
fi

# ============================================================================
# Create application directory
# ============================================================================

APP_DIR="/opt/petalia"
mkdir -p "$APP_DIR"
cd "$APP_DIR"

# ============================================================================
# Create environment file
# ============================================================================

cat > "$APP_DIR/.env.production" <<'EOF'
# Petalia API Configuration — Auto-generated by Terraform user_data

# Application
NODE_ENV=production
PORT=${api_port}
LOG_LEVEL=info

# Database (use RDS Proxy endpoint instead of direct RDS)
DB_HOST=${db_host}
DB_PORT=5432
DB_NAME=${db_name}
DB_USER=${db_user}
DB_PASSWORD=${DB_PASSWORD}  # Set via Secrets Manager

# Redis (assume ElastiCache available, or local Redis)
REDIS_HOST=localhost
REDIS_PORT=6379
REDIS_PASSWORD=

# AWS
AWS_REGION=us-east-1
AWS_S3_BUCKET=petalia-backups-prod
AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

# Features
CORS_ORIGIN=https://petalia.com,https://app.petalia.com
JWT_SECRET=${JWT_SECRET}
JWT_EXPIRES_IN=24h
OTP_TTL=600

# External APIs
SENTINEL_HUB_API_KEY=${SENTINEL_HUB_API_KEY}
OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
WHATSAPP_BUSINESS_ACCOUNT_ID=${WHATSAPP_BUSINESS_ACCOUNT_ID}
WHATSAPP_BUSINESS_API_TOKEN=${WHATSAPP_BUSINESS_API_TOKEN}

# Notifications
SLACK_WEBHOOK=
BACKUP_EMAIL=

# Health check
HEALTH_CHECK_DB=true
HEALTH_CHECK_REDIS=true
EOF

echo "Environment file created at $APP_DIR/.env.production"

# ============================================================================
# Fetch secrets from AWS Secrets Manager (recommended for prod)
# ============================================================================

# Example: Fetch database password
if command -v aws &> /dev/null; then
  echo "Fetching secrets from AWS Secrets Manager..."

  # Get database password
  DB_PASSWORD=$(aws secretsmanager get-secret-value \
    --secret-id petalia-db-credentials \
    --region ${aws_region} \
    --query SecretString \
    --output text | jq -r .password)

  # Update environment file with fetched secrets
  sed -i "s|DB_PASSWORD=.*|DB_PASSWORD=$DB_PASSWORD|" "$APP_DIR/.env.production"

  echo "✅ Secrets loaded from Secrets Manager"
else
  echo "⚠️  AWS CLI not available, using environment variables for secrets"
fi

# ============================================================================
# Pull and run Docker container
# ============================================================================

echo "Pulling Docker image: ${docker_image}"
docker pull ${docker_image}

echo "Starting Petalia API container..."
docker run -d \
  --name petalia-api \
  --restart always \
  --env-file "$APP_DIR/.env.production" \
  -p ${api_port}:${api_port} \
  -v /var/log/petalia:/var/log/petalia \
  --log-driver awslogs \
  --log-opt awslogs-group=/aws/ec2/petalia \
  --log-opt awslogs-region=${aws_region} \
  --log-opt awslogs-stream=$$(hostname) \
  ${docker_image}

# Wait for container to start
sleep 5

if docker ps | grep -q petalia-api; then
  echo "✅ Petalia API container started successfully"
else
  echo "❌ Failed to start Petalia API container"
  docker logs petalia-api || true
  exit 1
fi

# ============================================================================
# Health check
# ============================================================================

echo "Waiting for API to become healthy..."
for i in {1..30}; do
  if curl -sf http://localhost:${api_port}/api/health > /dev/null 2>&1; then
    echo "✅ API is healthy"
    break
  fi
  echo "Attempt $i/30: Waiting for API..."
  sleep 2
done

# ============================================================================
# CloudWatch Logs group (create if not exists)
# ============================================================================

aws logs create-log-group --log-group-name /aws/ec2/petalia --region ${aws_region} || true
aws logs put-retention-policy --log-group-name /aws/ec2/petalia --retention-in-days 30 --region ${aws_region} || true

# ============================================================================
# Auto-restart on failure
# ============================================================================

cat > /usr/local/bin/petalia-health-check.sh <<'HEALTH_CHECK'
#!/bin/bash
# Periodic health check and restart if needed

while true; do
  if ! curl -sf http://localhost:3000/api/health > /dev/null 2>&1; then
    echo "❌ Health check failed, restarting Petalia API..." >> /var/log/petalia-health.log
    docker restart petalia-api
  fi
  sleep 60
done
HEALTH_CHECK

chmod +x /usr/local/bin/petalia-health-check.sh

# Systemd service for health check
cat > /etc/systemd/system/petalia-health-check.service <<'SERVICE'
[Unit]
Description=Petalia API Health Check
After=docker.service
Requires=docker.service

[Service]
Type=simple
ExecStart=/usr/local/bin/petalia-health-check.sh
Restart=always
RestartSec=10
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
SERVICE

systemctl daemon-reload
systemctl enable petalia-health-check.service
systemctl start petalia-health-check.service

# ============================================================================
# Summary
# ============================================================================

echo ""
echo "=== Petalia API User Data Script Completed ==="
echo "Instance: $(hostname)"
echo "API URL: http://$(ec2-metadata --local-ipv4 | cut -d ' ' -f 2):${api_port}"
echo "Health Check: http://$(ec2-metadata --local-ipv4 | cut -d ' ' -f 2):${api_port}/api/health"
echo "Logs: /var/log/petalia/* and CloudWatch Logs"
echo "=== $(date) ==="
